// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lddirichlet
double lddirichlet(const Eigen::VectorXd& x, const Eigen::VectorXd& alphas);
RcppExport SEXP _BOBgmms_lddirichlet(SEXP xSEXP, SEXP alphasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alphas(alphasSEXP);
    rcpp_result_gen = Rcpp::wrap(lddirichlet(x, alphas));
    return rcpp_result_gen;
END_RCPP
}
// ldinvwishart
double ldinvwishart(const Eigen::MatrixXd& Sigma, const Eigen::MatrixXd& S, const double nu);
RcppExport SEXP _BOBgmms_ldinvwishart(SEXP SigmaSEXP, SEXP SSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(ldinvwishart(Sigma, S, nu));
    return rcpp_result_gen;
END_RCPP
}
// lmvgamma
double lmvgamma(double x, int p);
RcppExport SEXP _BOBgmms_lmvgamma(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lmvgamma(x, p));
    return rcpp_result_gen;
END_RCPP
}
// e_step
Eigen::MatrixXd e_step(const Eigen::MatrixXd& y, const std::vector<Eigen::VectorXd>& means, const std::vector<Eigen::MatrixXd>& covs, const Eigen::VectorXd probs, const Eigen::VectorXd& lik_weights, const double temp);
RcppExport SEXP _BOBgmms_e_step(SEXP ySEXP, SEXP meansSEXP, SEXP covsSEXP, SEXP probsSEXP, SEXP lik_weightsSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type covs(covsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lik_weights(lik_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(e_step(y, means, covs, probs, lik_weights, temp));
    return rcpp_result_gen;
END_RCPP
}
// em_optim_cpp_
Rcpp::List em_optim_cpp_(const Eigen::MatrixXd& y, std::vector<Eigen::VectorXd>& means_init, std::vector<Eigen::MatrixXd>& covs_init, Eigen::VectorXd probs_init, const Eigen::VectorXd& alphas, const std::vector<Eigen::VectorXd>& betas, const Eigen::VectorXd& lambdas, const Eigen::VectorXd& nus, const std::vector<Eigen::MatrixXd>& Psis, const Eigen::VectorXd& lik_weights, const Eigen::VectorXd& means_weights, const Eigen::VectorXd& covs_weights, const Eigen::VectorXd& probs_weights, const double a, const double b, const double c, const double r, int max_iters, double epss);
RcppExport SEXP _BOBgmms_em_optim_cpp_(SEXP ySEXP, SEXP means_initSEXP, SEXP covs_initSEXP, SEXP probs_initSEXP, SEXP alphasSEXP, SEXP betasSEXP, SEXP lambdasSEXP, SEXP nusSEXP, SEXP PsisSEXP, SEXP lik_weightsSEXP, SEXP means_weightsSEXP, SEXP covs_weightsSEXP, SEXP probs_weightsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP rSEXP, SEXP max_itersSEXP, SEXP epssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::VectorXd>& >::type means_init(means_initSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type covs_init(covs_initSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type probs_init(probs_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type nus(nusSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type Psis(PsisSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lik_weights(lik_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type means_weights(means_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type covs_weights(covs_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type probs_weights(probs_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< double >::type epss(epssSEXP);
    rcpp_result_gen = Rcpp::wrap(em_optim_cpp_(y, means_init, covs_init, probs_init, alphas, betas, lambdas, nus, Psis, lik_weights, means_weights, covs_weights, probs_weights, a, b, c, r, max_iters, epss));
    return rcpp_result_gen;
END_RCPP
}
// get_beta_bar
Eigen::VectorXd get_beta_bar(const Eigen::VectorXd& beta_vec, const Eigen::VectorXd& w_mean, const double lambda_tilde, const double lambda_bar, const double n_tilde);
RcppExport SEXP _BOBgmms_get_beta_bar(SEXP beta_vecSEXP, SEXP w_meanSEXP, SEXP lambda_tildeSEXP, SEXP lambda_barSEXP, SEXP n_tildeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w_mean(w_meanSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_tilde(lambda_tildeSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_bar(lambda_barSEXP);
    Rcpp::traits::input_parameter< const double >::type n_tilde(n_tildeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_beta_bar(beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde));
    return rcpp_result_gen;
END_RCPP
}
// get_Psi_bar
Eigen::MatrixXd get_Psi_bar(const Eigen::MatrixXd& Psi_tilde, const Eigen::MatrixXd& w_ssr, const Eigen::VectorXd& beta_vec, const Eigen::VectorXd& w_mean, const double lambda_tilde, const double lambda_bar, const double n_tilde);
RcppExport SEXP _BOBgmms_get_Psi_bar(SEXP Psi_tildeSEXP, SEXP w_ssrSEXP, SEXP beta_vecSEXP, SEXP w_meanSEXP, SEXP lambda_tildeSEXP, SEXP lambda_barSEXP, SEXP n_tildeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Psi_tilde(Psi_tildeSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type w_ssr(w_ssrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w_mean(w_meanSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_tilde(lambda_tildeSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_bar(lambda_barSEXP);
    Rcpp::traits::input_parameter< const double >::type n_tilde(n_tildeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_Psi_bar(Psi_tilde, w_ssr, beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BOBgmms_lddirichlet", (DL_FUNC) &_BOBgmms_lddirichlet, 2},
    {"_BOBgmms_ldinvwishart", (DL_FUNC) &_BOBgmms_ldinvwishart, 3},
    {"_BOBgmms_lmvgamma", (DL_FUNC) &_BOBgmms_lmvgamma, 2},
    {"_BOBgmms_e_step", (DL_FUNC) &_BOBgmms_e_step, 6},
    {"_BOBgmms_em_optim_cpp_", (DL_FUNC) &_BOBgmms_em_optim_cpp_, 19},
    {"_BOBgmms_get_beta_bar", (DL_FUNC) &_BOBgmms_get_beta_bar, 5},
    {"_BOBgmms_get_Psi_bar", (DL_FUNC) &_BOBgmms_get_Psi_bar, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BOBgmms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
