// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// batchOneShot
Eigen::VectorXd batchOneShot(double x_likelihood, Eigen::VectorXd x_mus, Eigen::VectorXd x_sigmas, double x_probs, const Eigen::MatrixXd& y, std::vector<Eigen::VectorXd>& mus, std::vector<Eigen::MatrixXd>& Sigmas, Eigen::VectorXd probs, const double a, const double b, const double c, const double r, const Eigen::VectorXd& alphas, const std::vector<Eigen::VectorXd>& betas, const Eigen::VectorXd& lambdas, const Eigen::VectorXd& nus, const std::vector<Eigen::MatrixXd>& Psis);
RcppExport SEXP _BOBgmms_batchOneShot(SEXP x_likelihoodSEXP, SEXP x_musSEXP, SEXP x_sigmasSEXP, SEXP x_probsSEXP, SEXP ySEXP, SEXP musSEXP, SEXP SigmasSEXP, SEXP probsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP rSEXP, SEXP alphasSEXP, SEXP betasSEXP, SEXP lambdasSEXP, SEXP nusSEXP, SEXP PsisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x_likelihood(x_likelihoodSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x_mus(x_musSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x_sigmas(x_sigmasSEXP);
    Rcpp::traits::input_parameter< double >::type x_probs(x_probsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::VectorXd>& >::type mus(musSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type Sigmas(SigmasSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type nus(nusSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type Psis(PsisSEXP);
    rcpp_result_gen = Rcpp::wrap(batchOneShot(x_likelihood, x_mus, x_sigmas, x_probs, y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis));
    return rcpp_result_gen;
END_RCPP
}
// tv_distance
double tv_distance(const Eigen::MatrixXd& target, const Eigen::MatrixXd& approx, const double step);
RcppExport SEXP _BOBgmms_tv_distance(SEXP targetSEXP, SEXP approxSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< const double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_distance(target, approx, step));
    return rcpp_result_gen;
END_RCPP
}
// ks_distance
double ks_distance(const Eigen::MatrixXd& target, const Eigen::MatrixXd& approx, const double step);
RcppExport SEXP _BOBgmms_ks_distance(SEXP targetSEXP, SEXP approxSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< const double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_distance(target, approx, step));
    return rcpp_result_gen;
END_RCPP
}
// em_optim
Eigen::VectorXd em_optim(const Eigen::MatrixXd& y, std::vector<Eigen::VectorXd>& mus, std::vector<Eigen::MatrixXd>& Sigmas, Eigen::VectorXd probs, const double a, const double b, const double c, const double r, const Eigen::VectorXd& lik_weights, const Eigen::VectorXd& mean_weights, const Eigen::VectorXd& cov_weights, const double prob_weights, const Eigen::VectorXd& alphas, const std::vector<Eigen::VectorXd>& betas, const Eigen::VectorXd& lambdas, const Eigen::VectorXd& nus, const std::vector<Eigen::MatrixXd>& Psis, int max_iters, double epss);
RcppExport SEXP _BOBgmms_em_optim(SEXP ySEXP, SEXP musSEXP, SEXP SigmasSEXP, SEXP probsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP rSEXP, SEXP lik_weightsSEXP, SEXP mean_weightsSEXP, SEXP cov_weightsSEXP, SEXP prob_weightsSEXP, SEXP alphasSEXP, SEXP betasSEXP, SEXP lambdasSEXP, SEXP nusSEXP, SEXP PsisSEXP, SEXP max_itersSEXP, SEXP epssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::VectorXd>& >::type mus(musSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type Sigmas(SigmasSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lik_weights(lik_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean_weights(mean_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type cov_weights(cov_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type prob_weights(prob_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type nus(nusSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type Psis(PsisSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< double >::type epss(epssSEXP);
    rcpp_result_gen = Rcpp::wrap(em_optim(y, mus, Sigmas, probs, a, b, c, r, lik_weights, mean_weights, cov_weights, prob_weights, alphas, betas, lambdas, nus, Psis, max_iters, epss));
    return rcpp_result_gen;
END_RCPP
}
// post_pred
Eigen::MatrixXd post_pred(const Eigen::MatrixXd& post_draws, std::vector<Eigen::VectorXd> betas, std::vector<Eigen::MatrixXd>& Psis);
RcppExport SEXP _BOBgmms_post_pred(SEXP post_drawsSEXP, SEXP betasSEXP, SEXP PsisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type post_draws(post_drawsSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::VectorXd> >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type Psis(PsisSEXP);
    rcpp_result_gen = Rcpp::wrap(post_pred(post_draws, betas, Psis));
    return rcpp_result_gen;
END_RCPP
}
// wbbOneShot
Eigen::VectorXd wbbOneShot(const Eigen::MatrixXd& y, std::vector<Eigen::VectorXd>& mus, std::vector<Eigen::MatrixXd>& Sigmas, Eigen::VectorXd probs, const double a, const double b, const double c, const double r, const Eigen::VectorXd& alphas, const std::vector<Eigen::VectorXd>& betas, const Eigen::VectorXd& lambdas, const Eigen::VectorXd& nus, const std::vector<Eigen::MatrixXd>& Psis, const bool randPrior_w);
RcppExport SEXP _BOBgmms_wbbOneShot(SEXP ySEXP, SEXP musSEXP, SEXP SigmasSEXP, SEXP probsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP rSEXP, SEXP alphasSEXP, SEXP betasSEXP, SEXP lambdasSEXP, SEXP nusSEXP, SEXP PsisSEXP, SEXP randPrior_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::VectorXd>& >::type mus(musSEXP);
    Rcpp::traits::input_parameter< std::vector<Eigen::MatrixXd>& >::type Sigmas(SigmasSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type nus(nusSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type Psis(PsisSEXP);
    Rcpp::traits::input_parameter< const bool >::type randPrior_w(randPrior_wSEXP);
    rcpp_result_gen = Rcpp::wrap(wbbOneShot(y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis, randPrior_w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BOBgmms_batchOneShot", (DL_FUNC) &_BOBgmms_batchOneShot, 17},
    {"_BOBgmms_tv_distance", (DL_FUNC) &_BOBgmms_tv_distance, 3},
    {"_BOBgmms_ks_distance", (DL_FUNC) &_BOBgmms_ks_distance, 3},
    {"_BOBgmms_em_optim", (DL_FUNC) &_BOBgmms_em_optim, 19},
    {"_BOBgmms_post_pred", (DL_FUNC) &_BOBgmms_post_pred, 3},
    {"_BOBgmms_wbbOneShot", (DL_FUNC) &_BOBgmms_wbbOneShot, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_BOBgmms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
