# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lddirichlet <- function(x, alphas) {
    .Call('_BOBgmms_lddirichlet', PACKAGE = 'BOBgmms', x, alphas)
}

ldinvwishart <- function(Sigma, S, nu) {
    .Call('_BOBgmms_ldinvwishart', PACKAGE = 'BOBgmms', Sigma, S, nu)
}

lmvgamma <- function(x, p) {
    .Call('_BOBgmms_lmvgamma', PACKAGE = 'BOBgmms', x, p)
}

e_step <- function(y, means, covs, probs, lik_weights, temp) {
    .Call('_BOBgmms_e_step', PACKAGE = 'BOBgmms', y, means, covs, probs, lik_weights, temp)
}

em_optim_cpp_ <- function(y, means_init, covs_init, probs_init, alphas, betas, lambdas, nus, Psis, lik_weights, means_weights, covs_weights, probs_weights, a, b, c, r, max_iters, epss) {
    .Call('_BOBgmms_em_optim_cpp_', PACKAGE = 'BOBgmms', y, means_init, covs_init, probs_init, alphas, betas, lambdas, nus, Psis, lik_weights, means_weights, covs_weights, probs_weights, a, b, c, r, max_iters, epss)
}

get_beta_bar <- function(beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde) {
    .Call('_BOBgmms_get_beta_bar', PACKAGE = 'BOBgmms', beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde)
}

get_Psi_bar <- function(Psi_tilde, w_ssr, beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde) {
    .Call('_BOBgmms_get_Psi_bar', PACKAGE = 'BOBgmms', Psi_tilde, w_ssr, beta_vec, w_mean, lambda_tilde, lambda_bar, n_tilde)
}

