# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

batchOneShot <- function(x_likelihood, x_mus, x_sigmas, x_probs, y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis) {
    .Call('_BOBgmms_batchOneShot', PACKAGE = 'BOBgmms', x_likelihood, x_mus, x_sigmas, x_probs, y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis)
}

tv_distance <- function(target, approx, step) {
    .Call('_BOBgmms_tv_distance', PACKAGE = 'BOBgmms', target, approx, step)
}

ks_distance <- function(target, approx, step) {
    .Call('_BOBgmms_ks_distance', PACKAGE = 'BOBgmms', target, approx, step)
}

em_optim <- function(y, mus, Sigmas, probs, a, b, c, r, lik_weights, mean_weights, cov_weights, prob_weights, alphas, betas, lambdas, nus, Psis, max_iters, epss) {
    .Call('_BOBgmms_em_optim', PACKAGE = 'BOBgmms', y, mus, Sigmas, probs, a, b, c, r, lik_weights, mean_weights, cov_weights, prob_weights, alphas, betas, lambdas, nus, Psis, max_iters, epss)
}

post_pred <- function(post_draws, betas, Psis) {
    .Call('_BOBgmms_post_pred', PACKAGE = 'BOBgmms', post_draws, betas, Psis)
}

wbbOneShot <- function(y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis, randPrior_w) {
    .Call('_BOBgmms_wbbOneShot', PACKAGE = 'BOBgmms', y, mus, Sigmas, probs, a, b, c, r, alphas, betas, lambdas, nus, Psis, randPrior_w)
}

